/*
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.tests

import com.google.inject.Inject
import io.codekontor.opencypher.xtext.openCypher.Cypher
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(OpenCypherInjectorProvider)
class OpenCypherParsingTest {
	@Inject
	ParseHelper<Cypher> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
