/*
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class OpenCypherRuntimeModule extends AbstractOpenCypherRuntimeModule {
}
