/*
 * generated by Xtext 2.25.0
 */
package io.codekontor.opencypher.xtext.parser.antlr;

import com.google.inject.Inject;
import io.codekontor.opencypher.xtext.parser.antlr.internal.InternalOpenCypherParser;
import io.codekontor.opencypher.xtext.services.OpenCypherGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class OpenCypherParser extends AbstractAntlrParser {

	@Inject
	private OpenCypherGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOpenCypherParser createParser(XtextTokenStream stream) {
		return new InternalOpenCypherParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Cypher";
	}

	public OpenCypherGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OpenCypherGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
