/*
 * generated by Xtext 2.12.0
 */
package io.codekontor.opencypher.xtext.ide


/**
 * Use this class to register ide components.
 */
class OpenCypherIdeModule extends AbstractOpenCypherIdeModule {
}
