/*
 * generated by Xtext 2.15.0
 */
package io.codekontor.opencypher.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOpenCypherScopeProvider extends DelegatingScopeProvider {
}
