/**
 * generated by Xtext 2.15.0
 */
package io.codekontor.opencypher.xtext.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Shortest Paths</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getAllShortestPaths()
 * @model
 * @generated
 */
public interface AllShortestPaths extends ShortestPathPattern
{
} // AllShortestPaths
