/**
 * generated by Xtext 2.15.0
 */
package io.codekontor.opencypher.xtext.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Anonymous Pattern Part</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getAnonymousPatternPart()
 * @model
 * @generated
 */
public interface AnonymousPatternPart extends PatternPart
{
} // AnonymousPatternPart
