/**
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Relationship Property Existence Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getCreateRelationshipPropertyExistenceConstraint()
 * @model
 * @generated
 */
public interface CreateRelationshipPropertyExistenceConstraint extends Command
{
} // CreateRelationshipPropertyExistenceConstraint
