/**
 * generated by Xtext 2.25.0
 */
package io.codekontor.opencypher.xtext.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Unique Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getCreateUniqueConstraint()
 * @model
 * @generated
 */
public interface CreateUniqueConstraint extends Command
{
} // CreateUniqueConstraint
