/**
 * generated by Xtext 2.25.0
 */
package io.codekontor.opencypher.xtext.openCypher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getHint()
 * @model
 * @generated
 */
public interface Hint extends EObject
{
} // Hint
