/**
 * generated by Xtext 2.25.0
 */
package io.codekontor.opencypher.xtext.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Identified Index Lookup</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.IdentifiedIndexLookup#getIndexName <em>Index Name</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.IdentifiedIndexLookup#getKey <em>Key</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.IdentifiedIndexLookup#getValue <em>Value</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.IdentifiedIndexLookup#getLegacyParameter <em>Legacy Parameter</em>}</li>
 * </ul>
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIdentifiedIndexLookup()
 * @model
 * @generated
 */
public interface IdentifiedIndexLookup extends NodeLookup, RelationshipLookup
{
  /**
   * Returns the value of the '<em><b>Index Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index Name</em>' attribute.
   * @see #setIndexName(String)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIdentifiedIndexLookup_IndexName()
   * @model
   * @generated
   */
  String getIndexName();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.IdentifiedIndexLookup#getIndexName <em>Index Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index Name</em>' attribute.
   * @see #getIndexName()
   * @generated
   */
  void setIndexName(String value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIdentifiedIndexLookup_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.IdentifiedIndexLookup#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIdentifiedIndexLookup_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.IdentifiedIndexLookup#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Legacy Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Legacy Parameter</em>' containment reference.
   * @see #setLegacyParameter(LegacyParameter)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIdentifiedIndexLookup_LegacyParameter()
   * @model containment="true"
   * @generated
   */
  LegacyParameter getLegacyParameter();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.IdentifiedIndexLookup#getLegacyParameter <em>Legacy Parameter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Legacy Parameter</em>' containment reference.
   * @see #getLegacyParameter()
   * @generated
   */
  void setLegacyParameter(LegacyParameter value);

} // IdentifiedIndexLookup
