/**
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.openCypher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Implicit Procedure Invocation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.ImplicitProcedureInvocation#getProcedureName <em>Procedure Name</em>}</li>
 * </ul>
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getImplicitProcedureInvocation()
 * @model
 * @generated
 */
public interface ImplicitProcedureInvocation extends EObject
{
  /**
   * Returns the value of the '<em><b>Procedure Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedure Name</em>' containment reference.
   * @see #setProcedureName(ProcedureName)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getImplicitProcedureInvocation_ProcedureName()
   * @model containment="true"
   * @generated
   */
  ProcedureName getProcedureName();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.ImplicitProcedureInvocation#getProcedureName <em>Procedure Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Procedure Name</em>' containment reference.
   * @see #getProcedureName()
   * @generated
   */
  void setProcedureName(ProcedureName value);

} // ImplicitProcedureInvocation
