/**
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.openCypher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Index</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.Index#getNodeLabel <em>Node Label</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.Index#getPropertyKeyName <em>Property Key Name</em>}</li>
 * </ul>
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIndex()
 * @model
 * @generated
 */
public interface Index extends EObject
{
  /**
   * Returns the value of the '<em><b>Node Label</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Label</em>' containment reference.
   * @see #setNodeLabel(NodeLabel)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIndex_NodeLabel()
   * @model containment="true"
   * @generated
   */
  NodeLabel getNodeLabel();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.Index#getNodeLabel <em>Node Label</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Label</em>' containment reference.
   * @see #getNodeLabel()
   * @generated
   */
  void setNodeLabel(NodeLabel value);

  /**
   * Returns the value of the '<em><b>Property Key Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Key Name</em>' attribute.
   * @see #setPropertyKeyName(String)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIndex_PropertyKeyName()
   * @model
   * @generated
   */
  String getPropertyKeyName();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.Index#getPropertyKeyName <em>Property Key Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Key Name</em>' attribute.
   * @see #getPropertyKeyName()
   * @generated
   */
  void setPropertyKeyName(String value);

} // Index
