/**
 * generated by Xtext 2.15.0
 */
package io.codekontor.opencypher.xtext.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Index Range Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.IndexRangeExpression#getLower <em>Lower</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.IndexRangeExpression#getUpper <em>Upper</em>}</li>
 * </ul>
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIndexRangeExpression()
 * @model
 * @generated
 */
public interface IndexRangeExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Lower</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lower</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lower</em>' containment reference.
   * @see #setLower(Expression)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIndexRangeExpression_Lower()
   * @model containment="true"
   * @generated
   */
  Expression getLower();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.IndexRangeExpression#getLower <em>Lower</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lower</em>' containment reference.
   * @see #getLower()
   * @generated
   */
  void setLower(Expression value);

  /**
   * Returns the value of the '<em><b>Upper</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Upper</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Upper</em>' containment reference.
   * @see #setUpper(Expression)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getIndexRangeExpression_Upper()
   * @model containment="true"
   * @generated
   */
  Expression getUpper();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.IndexRangeExpression#getUpper <em>Upper</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Upper</em>' containment reference.
   * @see #getUpper()
   * @generated
   */
  void setUpper(Expression value);

} // IndexRangeExpression
