/**
 * generated by Xtext 2.25.0
 */
package io.codekontor.opencypher.xtext.openCypher;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Merge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.Merge#getPatternPart <em>Pattern Part</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.Merge#getMergeActions <em>Merge Actions</em>}</li>
 * </ul>
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getMerge()
 * @model
 * @generated
 */
public interface Merge extends UpdatingClause
{
  /**
   * Returns the value of the '<em><b>Pattern Part</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern Part</em>' containment reference.
   * @see #setPatternPart(PatternPart)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getMerge_PatternPart()
   * @model containment="true"
   * @generated
   */
  PatternPart getPatternPart();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.Merge#getPatternPart <em>Pattern Part</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern Part</em>' containment reference.
   * @see #getPatternPart()
   * @generated
   */
  void setPatternPart(PatternPart value);

  /**
   * Returns the value of the '<em><b>Merge Actions</b></em>' containment reference list.
   * The list contents are of type {@link io.codekontor.opencypher.xtext.openCypher.MergeAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Merge Actions</em>' containment reference list.
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getMerge_MergeActions()
   * @model containment="true"
   * @generated
   */
  EList<MergeAction> getMergeActions();

} // Merge
