/**
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.openCypher;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.PatternElement#getNodepattern <em>Nodepattern</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.PatternElement#getChain <em>Chain</em>}</li>
 * </ul>
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getPatternElement()
 * @model
 * @generated
 */
public interface PatternElement extends AnonymousPatternPart
{
  /**
   * Returns the value of the '<em><b>Nodepattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodepattern</em>' containment reference.
   * @see #setNodepattern(NodePattern)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getPatternElement_Nodepattern()
   * @model containment="true"
   * @generated
   */
  NodePattern getNodepattern();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.PatternElement#getNodepattern <em>Nodepattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nodepattern</em>' containment reference.
   * @see #getNodepattern()
   * @generated
   */
  void setNodepattern(NodePattern value);

  /**
   * Returns the value of the '<em><b>Chain</b></em>' containment reference list.
   * The list contents are of type {@link io.codekontor.opencypher.xtext.openCypher.PatternElementChain}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chain</em>' containment reference list.
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getPatternElement_Chain()
   * @model containment="true"
   * @generated
   */
  EList<PatternElementChain> getChain();

} // PatternElement
