/**
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.openCypher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Periodic Commit Hint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.PeriodicCommitHint#getNumberOfRowsPerCommit <em>Number Of Rows Per Commit</em>}</li>
 * </ul>
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getPeriodicCommitHint()
 * @model
 * @generated
 */
public interface PeriodicCommitHint extends EObject
{
  /**
   * Returns the value of the '<em><b>Number Of Rows Per Commit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number Of Rows Per Commit</em>' containment reference.
   * @see #setNumberOfRowsPerCommit(DecimalInteger)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getPeriodicCommitHint_NumberOfRowsPerCommit()
   * @model containment="true"
   * @generated
   */
  DecimalInteger getNumberOfRowsPerCommit();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.PeriodicCommitHint#getNumberOfRowsPerCommit <em>Number Of Rows Per Commit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number Of Rows Per Commit</em>' containment reference.
   * @see #getNumberOfRowsPerCommit()
   * @generated
   */
  void setNumberOfRowsPerCommit(DecimalInteger value);

} // PeriodicCommitHint
