/**
 * generated by Xtext 2.15.0
 */
package io.codekontor.opencypher.xtext.openCypher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getProperties()
 * @model
 * @generated
 */
public interface Properties extends EObject
{
} // Properties
