/**
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reading Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getReadingClause()
 * @model
 * @generated
 */
public interface ReadingClause extends Clause
{
} // ReadingClause
