/**
 * generated by Xtext 2.15.0
 */
package io.codekontor.opencypher.xtext.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Remove Item</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getRemoveItem()
 * @model
 * @generated
 */
public interface RemoveItem extends NodeLabels
{
} // RemoveItem
