/**
 * generated by Xtext 2.25.0
 */
package io.codekontor.opencypher.xtext.openCypher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Union</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.Union#isAll <em>All</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.Union#getSingleQuery <em>Single Query</em>}</li>
 * </ul>
 *
 * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getUnion()
 * @model
 * @generated
 */
public interface Union extends EObject
{
  /**
   * Returns the value of the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>All</em>' attribute.
   * @see #setAll(boolean)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getUnion_All()
   * @model
   * @generated
   */
  boolean isAll();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.Union#isAll <em>All</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>All</em>' attribute.
   * @see #isAll()
   * @generated
   */
  void setAll(boolean value);

  /**
   * Returns the value of the '<em><b>Single Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Single Query</em>' containment reference.
   * @see #setSingleQuery(SingleQuery)
   * @see io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage#getUnion_SingleQuery()
   * @model containment="true"
   * @generated
   */
  SingleQuery getSingleQuery();

  /**
   * Sets the value of the '{@link io.codekontor.opencypher.xtext.openCypher.Union#getSingleQuery <em>Single Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Single Query</em>' containment reference.
   * @see #getSingleQuery()
   * @generated
   */
  void setSingleQuery(SingleQuery value);

} // Union
