/**
 * generated by Xtext 2.25.0
 */
package io.codekontor.opencypher.xtext.openCypher.impl;

import io.codekontor.opencypher.xtext.openCypher.Cypher;
import io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage;
import io.codekontor.opencypher.xtext.openCypher.QueryOptions;
import io.codekontor.opencypher.xtext.openCypher.Statement;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cypher</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.impl.CypherImpl#getQueryOptions <em>Query Options</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.impl.CypherImpl#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CypherImpl extends MinimalEObjectImpl.Container implements Cypher
{
  /**
   * The cached value of the '{@link #getQueryOptions() <em>Query Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQueryOptions()
   * @generated
   * @ordered
   */
  protected QueryOptions queryOptions;

  /**
   * The cached value of the '{@link #getStatements() <em>Statements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatements()
   * @generated
   * @ordered
   */
  protected EList<Statement> statements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CypherImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.CYPHER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QueryOptions getQueryOptions()
  {
    return queryOptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetQueryOptions(QueryOptions newQueryOptions, NotificationChain msgs)
  {
    QueryOptions oldQueryOptions = queryOptions;
    queryOptions = newQueryOptions;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenCypherPackage.CYPHER__QUERY_OPTIONS, oldQueryOptions, newQueryOptions);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQueryOptions(QueryOptions newQueryOptions)
  {
    if (newQueryOptions != queryOptions)
    {
      NotificationChain msgs = null;
      if (queryOptions != null)
        msgs = ((InternalEObject)queryOptions).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.CYPHER__QUERY_OPTIONS, null, msgs);
      if (newQueryOptions != null)
        msgs = ((InternalEObject)newQueryOptions).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.CYPHER__QUERY_OPTIONS, null, msgs);
      msgs = basicSetQueryOptions(newQueryOptions, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.CYPHER__QUERY_OPTIONS, newQueryOptions, newQueryOptions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Statement> getStatements()
  {
    if (statements == null)
    {
      statements = new EObjectContainmentEList<Statement>(Statement.class, this, OpenCypherPackage.CYPHER__STATEMENTS);
    }
    return statements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenCypherPackage.CYPHER__QUERY_OPTIONS:
        return basicSetQueryOptions(null, msgs);
      case OpenCypherPackage.CYPHER__STATEMENTS:
        return ((InternalEList<?>)getStatements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenCypherPackage.CYPHER__QUERY_OPTIONS:
        return getQueryOptions();
      case OpenCypherPackage.CYPHER__STATEMENTS:
        return getStatements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenCypherPackage.CYPHER__QUERY_OPTIONS:
        setQueryOptions((QueryOptions)newValue);
        return;
      case OpenCypherPackage.CYPHER__STATEMENTS:
        getStatements().clear();
        getStatements().addAll((Collection<? extends Statement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.CYPHER__QUERY_OPTIONS:
        setQueryOptions((QueryOptions)null);
        return;
      case OpenCypherPackage.CYPHER__STATEMENTS:
        getStatements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.CYPHER__QUERY_OPTIONS:
        return queryOptions != null;
      case OpenCypherPackage.CYPHER__STATEMENTS:
        return statements != null && !statements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CypherImpl
