/**
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.openCypher.impl;

import io.codekontor.opencypher.xtext.openCypher.IsNotNullExpression;
import io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Is Not Null Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IsNotNullExpressionImpl extends ExpressionImpl implements IsNotNullExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IsNotNullExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.IS_NOT_NULL_EXPRESSION;
  }

} //IsNotNullExpressionImpl
