/**
 * generated by Xtext 2.15.0
 */
package io.codekontor.opencypher.xtext.openCypher.impl;

import io.codekontor.opencypher.xtext.openCypher.IsNullExpression;
import io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Is Null Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IsNullExpressionImpl extends ExpressionImpl implements IsNullExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IsNullExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.IS_NULL_EXPRESSION;
  }

} //IsNullExpressionImpl
