/**
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.openCypher.impl;

import io.codekontor.opencypher.xtext.openCypher.LoadCSV;
import io.codekontor.opencypher.xtext.openCypher.LoadCSVQuery;
import io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage;
import io.codekontor.opencypher.xtext.openCypher.SingleQuery;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Load CSV Query</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.impl.LoadCSVQueryImpl#getLoadCSV <em>Load CSV</em>}</li>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.impl.LoadCSVQueryImpl#getSingleQuery <em>Single Query</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LoadCSVQueryImpl extends MinimalEObjectImpl.Container implements LoadCSVQuery
{
  /**
   * The cached value of the '{@link #getLoadCSV() <em>Load CSV</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoadCSV()
   * @generated
   * @ordered
   */
  protected LoadCSV loadCSV;

  /**
   * The cached value of the '{@link #getSingleQuery() <em>Single Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSingleQuery()
   * @generated
   * @ordered
   */
  protected SingleQuery singleQuery;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LoadCSVQueryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.LOAD_CSV_QUERY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LoadCSV getLoadCSV()
  {
    return loadCSV;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLoadCSV(LoadCSV newLoadCSV, NotificationChain msgs)
  {
    LoadCSV oldLoadCSV = loadCSV;
    loadCSV = newLoadCSV;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenCypherPackage.LOAD_CSV_QUERY__LOAD_CSV, oldLoadCSV, newLoadCSV);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLoadCSV(LoadCSV newLoadCSV)
  {
    if (newLoadCSV != loadCSV)
    {
      NotificationChain msgs = null;
      if (loadCSV != null)
        msgs = ((InternalEObject)loadCSV).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.LOAD_CSV_QUERY__LOAD_CSV, null, msgs);
      if (newLoadCSV != null)
        msgs = ((InternalEObject)newLoadCSV).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.LOAD_CSV_QUERY__LOAD_CSV, null, msgs);
      msgs = basicSetLoadCSV(newLoadCSV, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.LOAD_CSV_QUERY__LOAD_CSV, newLoadCSV, newLoadCSV));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SingleQuery getSingleQuery()
  {
    return singleQuery;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSingleQuery(SingleQuery newSingleQuery, NotificationChain msgs)
  {
    SingleQuery oldSingleQuery = singleQuery;
    singleQuery = newSingleQuery;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenCypherPackage.LOAD_CSV_QUERY__SINGLE_QUERY, oldSingleQuery, newSingleQuery);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSingleQuery(SingleQuery newSingleQuery)
  {
    if (newSingleQuery != singleQuery)
    {
      NotificationChain msgs = null;
      if (singleQuery != null)
        msgs = ((InternalEObject)singleQuery).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.LOAD_CSV_QUERY__SINGLE_QUERY, null, msgs);
      if (newSingleQuery != null)
        msgs = ((InternalEObject)newSingleQuery).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.LOAD_CSV_QUERY__SINGLE_QUERY, null, msgs);
      msgs = basicSetSingleQuery(newSingleQuery, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.LOAD_CSV_QUERY__SINGLE_QUERY, newSingleQuery, newSingleQuery));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenCypherPackage.LOAD_CSV_QUERY__LOAD_CSV:
        return basicSetLoadCSV(null, msgs);
      case OpenCypherPackage.LOAD_CSV_QUERY__SINGLE_QUERY:
        return basicSetSingleQuery(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenCypherPackage.LOAD_CSV_QUERY__LOAD_CSV:
        return getLoadCSV();
      case OpenCypherPackage.LOAD_CSV_QUERY__SINGLE_QUERY:
        return getSingleQuery();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenCypherPackage.LOAD_CSV_QUERY__LOAD_CSV:
        setLoadCSV((LoadCSV)newValue);
        return;
      case OpenCypherPackage.LOAD_CSV_QUERY__SINGLE_QUERY:
        setSingleQuery((SingleQuery)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.LOAD_CSV_QUERY__LOAD_CSV:
        setLoadCSV((LoadCSV)null);
        return;
      case OpenCypherPackage.LOAD_CSV_QUERY__SINGLE_QUERY:
        setSingleQuery((SingleQuery)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.LOAD_CSV_QUERY__LOAD_CSV:
        return loadCSV != null;
      case OpenCypherPackage.LOAD_CSV_QUERY__SINGLE_QUERY:
        return singleQuery != null;
    }
    return super.eIsSet(featureID);
  }

} //LoadCSVQueryImpl
