/**
 * generated by Xtext 2.21.0
 */
package io.codekontor.opencypher.xtext.openCypher.impl;

import io.codekontor.opencypher.xtext.openCypher.OpenCypherPackage;
import io.codekontor.opencypher.xtext.openCypher.VariableDeclaration;
import io.codekontor.opencypher.xtext.openCypher.VariableRef;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Variable Ref</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.codekontor.opencypher.xtext.openCypher.impl.VariableRefImpl#getVariableRef <em>Variable Ref</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VariableRefImpl extends ExpressionImpl implements VariableRef
{
  /**
   * The cached value of the '{@link #getVariableRef() <em>Variable Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariableRef()
   * @generated
   * @ordered
   */
  protected VariableDeclaration variableRef;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VariableRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.VARIABLE_REF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableDeclaration getVariableRef()
  {
    if (variableRef != null && variableRef.eIsProxy())
    {
      InternalEObject oldVariableRef = (InternalEObject)variableRef;
      variableRef = (VariableDeclaration)eResolveProxy(oldVariableRef);
      if (variableRef != oldVariableRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, OpenCypherPackage.VARIABLE_REF__VARIABLE_REF, oldVariableRef, variableRef));
      }
    }
    return variableRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VariableDeclaration basicGetVariableRef()
  {
    return variableRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariableRef(VariableDeclaration newVariableRef)
  {
    VariableDeclaration oldVariableRef = variableRef;
    variableRef = newVariableRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.VARIABLE_REF__VARIABLE_REF, oldVariableRef, variableRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenCypherPackage.VARIABLE_REF__VARIABLE_REF:
        if (resolve) return getVariableRef();
        return basicGetVariableRef();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenCypherPackage.VARIABLE_REF__VARIABLE_REF:
        setVariableRef((VariableDeclaration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.VARIABLE_REF__VARIABLE_REF:
        setVariableRef((VariableDeclaration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.VARIABLE_REF__VARIABLE_REF:
        return variableRef != null;
    }
    return super.eIsSet(featureID);
  }

} //VariableRefImpl
